
server:
  port: 9093


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/saga_inventory
    username: root
    password: example

  kafka:
    bootstrap-servers: "localhost:9092"
    #Kafka Producer Properties
    producer:
      topic: "tp-saga-orchestrator"
      group-id: "inventory"
    consumer:
      topic: "tp-saga-inventory"

  #JPA Properties
  jpa:
    hibernate:
      ddl-auto: update
